#!/usr/bin/env python3
import random
import skilstak.colors as c

# List of tiles

tiles = ["O", "#", "^", "|"]

# Creates map

w = 5
h = 5

map = [[0 for x in range(w)]for y in range (h)]


# Generates map

def generate():
    
    x = 4
    y = 4

    while x > -6:
        while y > -6:
            map[x][y] = random.choice(tiles)
            y -= 1
        x -= 1
        y = 4
        
generate()

# Places player unit

px1 = random.randrange(-5,-1)
py1 = random.randrange(-5,-1)
map[px1][py1] = c.blue + map[px1][py1] + c.reset 

# Prints map

c = -5

while c < 0: 
    print(map[-5][c] + map[-4][c] + map[-3][c] + map[-2][c] + map[-1][c])
    c += 
    
# Player Phase

print(
